{{- if .Values.persistence.volumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "archivy.fullname" . }}
  labels:
    {{- include "archivy.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.volumeClaim.storageClass }}
  storageClassName: {{ .Values.persistence.volumeClaim.storageClass | quote }}
  {{- else }}
  storageClassName: {{ include "archivy.fullname" . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.volumeClaim.size | quote }}
  volumeName: {{ include "archivy.fullname" . }}
{{- end }}
