{{- if .Values.persistence.volume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "archivy.fullname" . }}
  labels:
    {{- include "archivy.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.volume.storageClass }}
  storageClassName: {{ .Values.persistence.volume.storageClass | quote }}
  {{- else }}
  storageClassName: {{ include "archivy.fullname" . }}
  {{- end }}
  capacity:
    storage: {{ .Values.persistence.volume.size | quote }}
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.persistence.volume.path }}
    server: {{ .Values.persistence.volume.server }}
{{- end }}
